### ISSUE TITLE
basic feature show list todo

### ISSUE THREAD

**Issue by KotonoSora** [KotonoSora/todolist#1]
- [x] make recycle listview
- [x] make recycle adapter
- [x] make xml item
- [x] make viewmodel list data
- [x] make android test list data
- [x] make unit test for adapter

**Comment by KotonoSora** [comment]
Default base code not support full feature in android and kotlin
Convert dependencies older version to androidx
Config keystore for build release version

**Comment by KotonoSora** [comment]
Create recyclerview using viewmodel, databinding and livedata

Create layout recyclerview and item_view
Create TodoAdapter extends ListAdapter
Create TodoViewModel using LiveData
Binding layout, adapter, viewmodel in MainActivity

**Comment by KotonoSora** [comment]
Make unit test recyclerview and viewmodel

Create android test for todoviewmodel
Create android test for scroll to position on recyclerview
