### ISSUE TITLE
basic feature add new todo to list

### ISSUE THREAD

**Issue by KotonoSora** [KotonoSora/todolist#5]
- [x] make form input todo
- [x] make logic add todo to viewmodel
- [x] improve logic using viewmodel to share data after add new todo
- [x] local databse save todos
- [x] make logic to save new todo
- [x] add field description on screen add new
